package zombie.plz;

/** Generated by build.ps1 from java-patch/checksum-exempt.txt. Do not edit by hand. */
public final class PLZChecksumExemptList {
    private PLZChecksumExemptList() {
    }

    public static final String SOURCE_SHA256 = "AEDFE2DD6B0078C4E7D6DCC5EA109FF60E660A21116E19ED226C2BD48BBA2482";

    public static final String[] MOD_IDS = {  };

    public static final String[] AUTHORS = { "KI5" };

    public static final String[] EXCLUDED_MOD_IDS = {  };
}
