package zombie.plz;

/** Generated by build.ps1 on every build. Do not edit by hand; your changes will be overwritten. */
public final class PLZPatchBuild {
    private PLZPatchBuild() {
    }

    public static final String BUILT_AT = "2026-09-29";
    public static final String JAR_SHA256 = "E1A69EB743EDE60B213A0FE7F8B83D4FCAB773036D256CC4543A336F3B058A33";
    public static final String SHADOWED_CLASS_SHA256 = "E8192F87D88DA607ABE0293228C84EFBD822ED4AC0A331102C030BC3EEABA467";
}
